monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_input.*" }
      { node.name = "~alsa_output.*" }
    ]
    actions = {
      update-props = {
	session.suspend-timeout-seconds = 0
      }
    }
  }
]

monitor.alsa.properties = {
  session.suspend-timeout-seconds = 0
}

wireplumber.profiles = {
  main = {
    hooks.node.suspend = disabled
  }
}

default.configured-audio-sink = "easyeffects_sink"
