wallpaper {
    monitor =
    path = ~/images/icy-wolf.jpg
    fit_mode = cover
}

# wallpaper {
#     monitor =
#     path = ~/images/synthwave.jpg
#     fit_mode = cover
# }
#
# wallpaper {
#     monitor =
#     path = ~/images/moody.jpg
#     fit_mode = cover
# }
#
# wallpaper {
#     monitor =
#     path = ~/images/romantic.png
#     fit_mode = cover
# }
